version: 1.0.{build}

image: Visual Studio 2017

clone_folder: c:\azura

environment:
  NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip
  VULKAN_URL: https://vulkan.lunarg.com/sdk/download/1.1.77.0/windows/VulkanSDK-1.1.77.0-Installer.exe

  matrix:
    - BUILD: 'DEBUG'
      TARGET: 'Win64'

    - BUILD: 'RELEASE'
      TARGET: 'Win64'

matrix:
  fast_finish: true

platform:
  - x64

services:

build: off

install:
  # -------------------------- CACHE COMMANDS START --------------------------

  - ps: mkdir C:\AppveyorCache\ -ea 0
  - ps: mkdir C:\AppveyorCache\Ninja\ -ea 0
  - ps: mkdir C:\AppveyorCache\VulkanSDK\ -ea 0

  # Download Ninja
  - ps: appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - ps: 7z x ninja.zip -oC:\AppveyorCache\Ninja\ > nul

  # Download and setup Vulkan
  - ps: cd ..
  - ps: appveyor DownloadFile %VULKAN_URL% -FileName Vulkan.exe
  - ps: cmd /c "Vulkan.exe /S"
  - ps: Copy-Item -Path "C:\VulkanSDK\*" -Destination "C:\AppveyorCache\VulkanSDK\" -Recurse -Force 

  # -------------------------- CACHE COMMANDS END --------------------------

  # Copy Ninja from Cache to Repo
  - ps: mkdir C:\azura\External\Windows\Tools\Ninja\ -ea 0
  - ps: Copy-Item -Path "C:\AppveyorCache\Ninja\*" -Destination "C:\azura\External\Windows\Tools\Ninja\" -Recurse -Force 
  - ps: C:\azura\External\Windows\Tools\Ninja\ninja.exe --version

  # Copy VulkanSDK from Cache to Repo
  - ps: mkdir C:\azura\Source\Imports\Windows\Vulkan\ -ea 0
  - ps: Copy-Item -Path "C:\AppveyorCache\VulkanSDK\*" -Destination "C:\azura\Source\Imports\Windows\Vulkan\" -Recurse -Force
  - ps: cd C:\azura\Source\Imports\Windows\Vulkan\
  - ps: dir

before_test:
  - cd C:\azura
  - C:\Python27\python.exe build.py --project all --target %TARGET% --configFile ./External/AppveyorConfig.ini --build %BUILD%

test_script:

after_test:

cache:
  - C:\AppveyorCache\Ninja\ -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

# artifacts:
#   # pushing a single file
#   - path: test.zip

#   # pushing a single file with environment variable in path and "Deployment name" specified
#   - path: MyProject\bin\$(configuration)
#     name: myapp

#   # pushing entire folder as a zip archive
#   - path: logs

#   # pushing all *.nupkg files in build directory recursively
#   - path: '**\*.nupkg'
