version: 1.0.{build}

image: Visual Studio 2017

clone_folder: c:\azura

environment:
  NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip
  VULKAN_URL: https://vulkan.lunarg.com/sdk/download/1.1.77.0/windows/VulkanSDK-1.1.77.0-Installer.exe
  BOOST_URL: https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.7z
  GLFW_64_URL: https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.bin.WIN64.zip
  GLFW_32_URL: https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.bin.WIN32.zip

  matrix:
    - BUILD: 'DEBUG'
      TARGET: 'Win64'

    - BUILD: 'DEBUG'
      TARGET: 'Win32'

matrix:
  fast_finish: true

platform:
  - x64

services:

build: off

install:
  - ps: git submodule -q update --init

  # -------------------------- CACHE CHECK --------------------------

  - ps: ./Scripts/Build/appveyor_cache.ps1

  # -------------------------- CACHE CHECK --------------------------

  # Copy Ninja from Cache to Repo
  - ps: mkdir C:\azura\External\Windows\Tools\Ninja\ -ea 0 > $null
  - ps: Copy-Item -Path "C:\AppveyorCache\Ninja\*" -Destination "C:\azura\External\Windows\Tools\Ninja\" -Recurse -Force
  - ps: C:\azura\External\Windows\Tools\Ninja\ninja.exe --version

before_test:
  - cd C:\azura
  - C:\Python27\python.exe build.py --project all --target %TARGET% --configFile ./External/AppveyorConfig.ini --cmakeConfigFile="External/AppveyorCMakeConfig.ini" --build %BUILD% --includeTests

test_script:

after_test:

cache:
  - C:\AppveyorCache\ -> .cicache

# artifacts:
#   # pushing a single file
#   - path: test.zip

#   # pushing a single file with environment variable in path and "Deployment name" specified
#   - path: MyProject\bin\$(configuration)
#     name: myapp

#   # pushing entire folder as a zip archive
#   - path: logs

#   # pushing all *.nupkg files in build directory recursively
#   - path: '**\*.nupkg'
