version: 1.0.{build}

image: Visual Studio 2017

clone_folder: c:\azura

environment:
  NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip
  VULKAN_URL: https://vulkan.lunarg.com/sdk/download/1.1.77.0/windows/VulkanSDK-1.1.77.0-Installer.exe
  BOOST_URL: https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.7z

  matrix:
    - BUILD: 'DEBUG'
      TARGET: 'Win64'

    - BUILD: 'RELEASE'
      TARGET: 'Win64'

matrix:
  fast_finish: true

platform:
  - x64

services:

build: off

install:
  # -------------------------- CACHE CHECK --------------------------

  - ps: ./Scripts/Build/appveyor_cache.ps1

  # -------------------------- CACHE CHECK --------------------------

  # Copy Ninja from Cache to Repo
  - ps: mkdir C:\azura\External\Windows\Tools\Ninja\ -ea 0
  - ps: Copy-Item -Path "C:\AppveyorCache\Ninja\*" -Destination "C:\azura\External\Windows\Tools\Ninja\" -Recurse -Force 
  - ps: C:\azura\External\Windows\Tools\Ninja\ninja.exe --version

  # Copy VulkanSDK from Cache to Repo
  - ps: mkdir C:\azura\Source\Imports\Windows\Vulkan\ -ea 0
  - ps: Copy-Item -Path "C:\AppveyorCache\VulkanSDK\*" -Destination "C:\azura\Source\Imports\Windows\Vulkan\" -Recurse -Force
  - ps: cd C:\azura\Source\Imports\Windows\Vulkan\
  - ps: dir

before_test:
  - cd C:\azura
  - C:\Python27\python.exe build.py --project all --target %TARGET% --configFile ./External/AppveyorConfig.ini --build %BUILD%

test_script:

after_test:

cache:
  - C:\AppveyorCache\ -> .cicache

# artifacts:
#   # pushing a single file
#   - path: test.zip

#   # pushing a single file with environment variable in path and "Deployment name" specified
#   - path: MyProject\bin\$(configuration)
#     name: myapp

#   # pushing entire folder as a zip archive
#   - path: logs

#   # pushing all *.nupkg files in build directory recursively
#   - path: '**\*.nupkg'
