version: "{build}"

image: Visual Studio 2017

branches:
  only:
    - master

skip_commits:
  message: /^Docs/

clone_folder: c:\azura

environment:
  AZURA_CONFIG: C:\azura\Config\appveyor\
  NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip
  VULKAN_URL: https://vulkan.lunarg.com/sdk/download/1.1.77.0/windows/VulkanSDK-1.1.77.0-Installer.exe
  BOOST_URL: https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.7z
  GLFW_64_URL: https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.bin.WIN64.zip
  GLFW_32_URL: https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.bin.WIN32.zip
  CMAKE_11_4_URL: https://cmake.org/files/v3.11/cmake-3.11.4-win64-x64.zip
  SLANG_COMPILER_URL: https://github.com/shader-slang/slang/releases/download/v0.11.16/slang-0.11.16-win64.zip
  LLVM_COMPILER_URL: http://releases.llvm.org/6.0.1/LLVM-6.0.1-win64.exe

  matrix:
    - BUILD: 'DEBUG'
      TARGET: 'Win64'

    - BUILD: 'RELEASE'
      TARGET: 'Win64'

# TODO(vasumahesh1):[WIN32]: Disabled for now.
    # - BUILD: 'DEBUG'
    #   TARGET: 'Win32'

    # - BUILD: 'RELEASE'
    #   TARGET: 'Win32'

matrix:
  fast_finish: true

platform:
  - x64

services:

build: off

install:
  - ps: git submodule -q update --init --recursive
  - ps: git submodule
  - ps: mkdir C:\azura\BuildLogs\ -ea 0 > $null
  - ps: dir "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC"

  # -------------------------- CACHE CHECK --------------------------

  - ps: ./Scripts/Build/appveyor_cache.ps1

  # -------------------------- CACHE CHECK --------------------------

  # Copy Ninja from Cache to Repo
  - ps: mkdir C:\azura\External\Windows\Tools\Ninja\ -ea 0 > $null
  - ps: Copy-Item -Path "C:\AppveyorCache\Ninja\*" -Destination "C:\azura\External\Windows\Tools\Ninja\" -Recurse -Force
  - ps: C:\azura\External\Windows\Tools\Ninja\ninja.exe --version

before_test:
  - cd C:\azura
  - C:\Python37-x64\python.exe build.py --project all --target %TARGET% --configFile ./External/AppveyorConfig.ini --cmakeConfigFile="External/AppveyorCMakeConfig.ini" --build %BUILD% --includeTests --deploy

test_script:

after_test:

cache:
  - C:\AppveyorCache\ -> .cicache

artifacts:
  - path: BuildLogs/DefaultStaticLog.log

  - path: Deploy/Win64_RELEASE/ProceduralPlanet/
    name: ProceduralPlanet
    type: zip

  - path: Deploy/Win64_RELEASE/ClothSim/
    name: ClothSim
    type: zip