version: 1.0.{build}

image: Visual Studio 2017

clone_folder: c:\azura

matrix:
  fast_finish: true

platform:
  - x86
  - x64

configuration:
  - Debug

services:

build: off

install:
  # Download Ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:/azura/External/Windows/Tools/Ninja/ > nul
  - C:\azura\External\Windows\Tools\Ninja\ninja.exe --version

  - cd ..
  - appveyor DownloadFile https://vulkan.lunarg.com/sdk/download/1.1.77.0/windows/VulkanSDK-1.1.77.0-Installer.exe -FileName Vulkan.exe
  - ps: ./Vulkan.exe /S
  - ps: type Vulkan.exe
  - ps: Move-Item -Path C:\VulkanSDK -Destination C:\azura\Source\Imports\Windows\Vulkan\
  - ps: cd C:\azura\Source\Imports\Windows\Vulkan\1.1.77.0\
  - ps: dir

# scripts to run before tests (working directory and environment changes are persisted from the previous steps such as "before_build")
before_test:
  - cd C:\azura
  - C:\Python27\python.exe build.py --project all --target t --configFile ./External/AppveyorConfig.ini

test_script:

after_test:

# artifacts:
#   # pushing a single file
#   - path: test.zip

#   # pushing a single file with environment variable in path and "Deployment name" specified
#   - path: MyProject\bin\$(configuration)
#     name: myapp

#   # pushing entire folder as a zip archive
#   - path: logs

#   # pushing all *.nupkg files in build directory recursively
#   - path: '**\*.nupkg'
