version: 1.0.{build}

image: Visual Studio 2017

clone_folder: c:\azura

environment:
  NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip
  VULKAN_URL: https://vulkan.lunarg.com/sdk/download/1.1.77.0/windows/VulkanSDK-1.1.77.0-Installer.exe

  matrix:
    - BUILD: 'DEBUG'
      TARGET: 'Win64'

    - BUILD: 'RELEASE'
      TARGET: 'Win64'

matrix:
  fast_finish: true

platform:
  - x64

services:

build: off

install:
  # Download Ninja
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:/azura/External/Windows/Tools/Ninja/ > nul
  - C:\azura\External\Windows\Tools\Ninja\ninja.exe --version

  # Download and setup Vulkan
  - cd ..
  - appveyor DownloadFile %VULKAN_URL% -FileName Vulkan.exe
  - Vulkan.exe /S
  - ps: mkdir C:\azura\Source\Imports\Windows\Vulkan\ -ea 0
  - ps: Copy-Item -Path "C:\VulkanSDK\*" -Destination "C:\azura\Source\Imports\Windows\Vulkan\" -Recurse -Force 

before_test:
  - cd C:\azura
  - C:\Python27\python.exe build.py --project all --target %TARGET% --configFile ./External/AppveyorConfig.ini --build %BUILD%

test_script:

after_test:

# artifacts:
#   # pushing a single file
#   - path: test.zip

#   # pushing a single file with environment variable in path and "Deployment name" specified
#   - path: MyProject\bin\$(configuration)
#     name: myapp

#   # pushing entire folder as a zip archive
#   - path: logs

#   # pushing all *.nupkg files in build directory recursively
#   - path: '**\*.nupkg'
