version: 1.0.{build}

image: Visual Studio 2017

clone_folder: c:\azura

matrix:
  fast_finish: true

platform:
  - x86
  - x64

configuration:
  - Debug

cache:
  - Tools\External

services:

install:
  # Download Ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:/azura/External/Windows/Tools/Ninja/ > nul
  - C:\azura\External\Windows\Tools\Ninja\ninja.exe --version

  - cd C:\azura
  - C:\Python27\python.exe build.py --project all --target t --configFile ./External/AppveyorConfig.ini

# artifacts:
#   # pushing a single file
#   - path: test.zip

#   # pushing a single file with environment variable in path and "Deployment name" specified
#   - path: MyProject\bin\$(configuration)
#     name: myapp

#   # pushing entire folder as a zip archive
#   - path: logs

#   # pushing all *.nupkg files in build directory recursively
#   - path: '**\*.nupkg'
